[workspace]
resolver = "2"
members = [
    "packages/tuigreat",
    "packages/voltui",
    "packages/nettui",
    "packages/blutui",
    "packages/kaltui",
    "packages/caltui",
    "packages/mustui",
]

[workspace.package]
version = "0.1.1"
edition = "2024"

[workspace.dependencies]
tuigreat = { path = "packages/tuigreat" }
ratatui = "0.29"
crossterm = "0.28"
serde_json = "1"
